name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Marcus-Johnson
          MAX_REPOS: 10
          # Point this to the new file you will create in step 2
          SETTING_JSON: profile-3d-settings.json

      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "chore: update 3D contribution graph"
          git push